[package]
name = "bssl-tls"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[dependencies.bssl-crypto]
path = "../bssl-crypto"

[dependencies.bssl-sys]
path = "../bssl-sys"

[dev-dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"

[features]
default = []
# `std` depends on the Rust `std` crate, but adds some useful trait impls if
# available.
std = ["bssl-crypto/std"]
# `mlalgs` enables ML-KEM and ML-DSA support. This requires Rust 1.82.
mlalgs = ["bssl-crypto/mlalgs"]
